services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/static
      - media_volume:/home/media
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/static
      - media_volume:/home/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
