# Generated by Django 5.1.1 on 2024-11-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_registration',
            field=models.CharField(choices=[('phone', 'Phone'), ('google', 'Google')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
